### ISSUE TITLE
php 8 compatibility

### ISSUE THREAD

**Issue by briaznar** [Avaaz/bouncestudio-php7#1]
Hello!

Now that PHP7.4 is at end of support, are you planning to release a version for php8?
when trying to install the extension with PHP. 8.1 I get the following error:

`php_bouncestudio.c:276:62: error: expected ')' before 'TSRMLS_CC'
     php_bouncestudio_entry = zend_register_internal_class(&bs TSRMLS_CC);
                                                              ^~~~~~~~~~`
thank you!

**Comment by lexabug** [comment]
Hello.

There were no plans to release a version for php8. But I'll try to do something about it.

**Comment by briaznar** [comment]
Thank you so much!
I was able to tweak this locally by removing the TSRMLS_CC. so 
`zend_register_internal_class(&bs);`

now I get a series of `Missing arginfo for bounceStudio_FUNCTION_NAME()`

**Comment by briaznar** [comment]
I see that this repo has a fork that makes it compatible for PHP 8

**Comment by lexabug** [comment]
> I see that this repo has a fork that makes it compatible for PHP 8

Great! I didn't know that someone has forked the repo. I think it's better to use that fork, because at the moment I have no capacity to port the extension at the moment.
